--/Universidad Nacional de La Matanza
--/Bases de Datos Aplicadas - Comision 02

--/Grupo 7 - Integrantes:
--Almiron, Luca
--Figueroa, Santiago
--Ruarte, Fidel
--Villalba, Leandro

--/Fecha: xx/xx/2026

--Creacion de Tablas

IF EXISTS (SELECT name FROM sys.databases WHERE name = 'MUNDIAL')
BEGIN
	USE MUNDIAL
END;
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'TABLAS' AND TABLE_NAME = 'Club')
BEGIN
	CREATE TABLE TABLAS.Club
	(
		IdClub INT PRIMARY KEY IDENTITY(1, 1),
		Nombre VARCHAR(20)
	);
END;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'TABLAS' AND TABLE_NAME = 'Persona')
BEGIN
	CREATE TABLE TABLAS.Persona
	(
		IdPersona INT PRIMARY KEY IDENTITY(1, 1),
		Nombre VARCHAR(30),
		Fnac DATE,
		Rol VARCHAR(10),
		Pais INT,
		FOREIGN KEY(Pais) REFERENCES TABLAS.Pais(IdPais)
	);
END;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'TABLAS' AND TABLE_NAME = 'Tecnico')
BEGIN
	CREATE TABLE TABLAS.Tecnico
	(
		IdTecnico INT,
		Funcion VARCHAR(40),
		Seleccion INT,
		TarjetasAcum INT,
		FOREIGN KEY(Seleccion) REFERENCES TABLAS.Seleccion(IdSeleccion),
		FOREIGN KEY(IdTecnico) REFERENCES TABLAS.Persona(IdPersona),
		PRIMARY KEY(IdTecnico)
	);
END;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'TABLAS' AND TABLE_NAME = 'Arbitro')
BEGIN
	CREATE TABLE TABLAS.Arbitro
	(
		IdArbitro INT,
		Categoria VARCHAR(20),
		FOREIGN KEY(IdArbitro) REFERENCES TABLAS.Persona(IdPersona),
		PRIMARY KEY(IdArbitro)
	);
END;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'TABLAS' AND TABLE_NAME = 'Jugador')
BEGIN
	CREATE TABLE TABLAS.Jugador
	(
		IdJugador INT,
		Estado VARCHAR(10),
		Posicion VARCHAR(20),
		Numero INT,
		Club INT NULL,
		Seleccion INT,
		TarjetasAcum INT,
		FOREIGN KEY(IdJugador) REFERENCES TABLAS.Persona(IdPersona),
		FOREIGN KEY(Club) REFERENCES TABLAS.Club(IdClub),
		FOREIGN KEY(Seleccion) REFERENCES TABLAS.Seleccion(IdSeleccion),
		PRIMARY KEY(IdJugador)
	);
END;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'TABLAS' AND TABLE_NAME = 'Idioma')
BEGIN
	CREATE TABLE TABLAS.Idioma
	(
		IdIdioma INT PRIMARY KEY IDENTITY(1, 1),
		Descripcion VARCHAR(20)
	)
END;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'TABLAS' AND TABLE_NAME = 'HablaIdioma')
BEGIN
	CREATE TABLE TABLAS.HablaIdioma
	(
		Arbitro INT,
		Idioma INT,
		FOREIGN KEY(Arbitro) REFERENCES TABLAS.Arbitro(IdArbitro),
		FOREIGN KEY(Idioma) REFERENCES TABLAS.Idioma(IdIdioma),
		PRIMARY KEY(Arbitro, Idioma)
	)
END;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'TABLAS' AND TABLE_NAME = 'Reporte')
BEGIN
	CREATE TABLE TABLAS.Reporte
	(
		IdReporte INT PRIMARY KEY IDENTITY(1, 1),
		Razon VARCHAR(20),
		Descripcion VARCHAR(300),
		Arbitro INT,
		Partido INT,
		FOREIGN KEY(Arbitro) REFERENCES TABLAS.Arbitro(IdArbitro),
		FOREIGN KEY(Partido) REFERENCES TABLAS.Partido(IdPartido)
	)
END;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'TABLAS' AND TABLE_NAME = 'Reporte')
BEGIN
	CREATE TABLE TABLAS.Arbitraje
	(
		Arbitro INT,
		Funcion VARCHAR(9),
		Partido INT,
		FOREIGN KEY(Arbitro) REFERENCES TABLAS.Arbitro(IdArbitro),
		FOREIGN KEY(Partido) REFERENCES TABLAS.Partido(IdPartido),
		PRIMARY KEY(Arbitro, Partido)
	)
END;
GO
