IF EXISTS (SELECT name FROM sys.databases WHERE name = 'MUNDIAL')
BEGIN
	USE MUNDIAL
END;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'TABLAS' AND TABLE_NAME = 'Pais')
BEGIN
	CREATE TABLE TABLAS.Pais
	(
		IdPais INT PRIMARY KEY IDENTITY(1, 1),
		Nombre varchar(30),
		Pbi decimal(4,2)
	);
END;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'TABLAS' AND TABLE_NAME = 'Seleccion')
BEGIN
	CREATE TABLE TABLAS.Seleccion
	(
		IdSeleccion INT PRIMARY KEY IDENTITY(1, 1),
		Confederacion VARCHAR(10)
	);
END;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'TABLAS' AND TABLE_NAME = 'Club')
BEGIN
	CREATE TABLE TABLAS.Club
	(
		IdClub INT PRIMARY KEY IDENTITY(1, 1),
		Nombre VARCHAR(20)
	);
END;
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'TABLAS' AND TABLE_NAME = 'Persona')
BEGIN
	CREATE TABLE TABLAS.Persona
	(
		IdPersona INT PRIMARY KEY IDENTITY(1, 1),
		Nombre VARCHAR(30),
		Fnac DATE,
		Rol VARCHAR(10),
		Pais INT,
		FOREIGN KEY(Pais) REFERENCES TABLAS.Pais(IdPais)
	);
END;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'TABLAS' AND TABLE_NAME = 'Tecnico')
BEGIN
	CREATE TABLE TABLAS.Tecnico
	(
		IdTecnico INT,
		Funcion VARCHAR(40),
		Seleccion INT,
		FOREIGN KEY(Seleccion) REFERENCES TABLAS.Seleccion(IdSeleccion),
		FOREIGN KEY(IdTecnico) REFERENCES TABLAS.Persona(IdPersona),
		PRIMARY KEY(IdTecnico)
	);
END;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'TABLAS' AND TABLE_NAME = 'Arbitro')
BEGIN
	CREATE TABLE TABLAS.Arbitro
	(
		IdArbitro INT,
		Categoria VARCHAR(20),
		FOREIGN KEY(IdArbitro) REFERENCES TABLAS.Persona(IdPersona),
		PRIMARY KEY(IdArbitro)
	);
END;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'TABLAS' AND TABLE_NAME = 'Jugador')
BEGIN
	CREATE TABLE TABLAS.Jugador
	(
		IdJugador INT,
		Estado VARCHAR(10),
		Posicion VARCHAR(20),
		Numero INT,
		Club INT NULL,
		Seleccion INT,
		TarjetasAcum INT,
		FOREIGN KEY(IdJugador) REFERENCES TABLAS.Persona(IdPersona),
		FOREIGN KEY(Club) REFERENCES TABLAS.Club(IdClub),
		FOREIGN KEY(Seleccion) REFERENCES TABLAS.Seleccion(IdSeleccion),
		PRIMARY KEY(IdJugador)
	);
END;
GO