USE db_mundial;
go
---------------------------------------------------------------
		--NOTAS A TENER EN CUENTA
--LO IDEAL SERIA MANTENER TODOS LOS ATRIBUTOS EN MAYUS
--ENTIDADES PRIMERA EN MAYUS 
--LAS FK TIENEN EL FORMATO 'FK_TABLAHIJA_TABLAMADRE'
--CUALQUIER RECOMENDACION AL GRUPO DE WSP
--SEAMOS ORDEANDOS PORFAVOR


IF OBJECT_ID('dbo.Pais','U') iS NULL
	CREATE TABLE Pais(
		ID_PAIS INT IDENTITY(1,1) CONSTRAINT PK_Pais PRIMARY KEY,
		NOMBRE VARCHAR(50) NOT NULL,
		PBI BIGINT
	);
IF OBJECT_ID('dbo.Mundial','U') is NULL
	CREATE TABLE Mundial(
		ID_MUNDIAL INT IDENTITY(1,1) CONSTRAINT PK_Mundial PRIMARY KEY,
		ID_PAIS INT NOT NULL CONSTRAINT FK_Mundial_Pais REFERENCES Pais(ID_PAIS),
		ACTIVIDAD_FECHA_INICIO DATE,
		ACTIVIDAD_FECHA_FIN DATE,
		TAMANIO_SELECCION_MINIMO INT NOT NULL,
		TAMANIO_SELECCION_MAXIMO INT NOT NULL,
		CAMBIOS_VENTANAS INT NOT NULL,
		CAMBIOS_CANTIDAD INT NOT NULL,
		SUSPENSION_TARJETAS_MAXIMAS INT NOT NULL,
		SUSPENSION_TIEMPO INT NOT NULL
	);
IF OBJECT_ID('dbo.Grupo','U') is NULL
	create TABLE Grupo(
		ID_GRUPO INT IDENTITY(1,1) CONSTRAINT PK_Grupo PRIMARY KEY,
		NOMBRE VARCHAR(10) NOT NULL
	);

IF OBJECT_ID('dbo.Seleccion','U') is NULL 
	create table Seleccion(
		ID_SELECCION INT IDENTITY(1,1) CONSTRAINT PK_Seleccion PRIMARY KEY,
		ID_PAIS INT NOT NULL CONSTRAINT FK_Pais_Seleccion REFERENCES Pais(ID_PAIS),
		ID_MUNDIAL INT NOT NULL CONSTRAINT FK_Seleccion_Mundial REFERENCES Mundial(ID_MUNDIAL),
		ID_GRUPO INT NOT NULL CONSTRAINT FK_Seleccion_Grupo REFERENCES Grupo(ID_GRUPO),
		CONFEDERACION VARCHAR(45) NOT NULL
	);
