USE db_mundial;
go
---------------------------------------------------------------
		--NOTAS A TENER EN CUENTA
--LO IDEAL SERIA MANTENER TODOS LOS ATRIBUTOS EN MAYUS
--ENTIDADES PRIMERA EN MAYUS 
--LAS FK TIENEN EL FORMATO 'FK_TABLAHIJA_TABLAMADRE'
--CUALQUIER RECOMENDACION AL GRUPO DE WSP
--SEAMOS ORDEANDOS PORFAVOR


IF OBJECT_ID('dbo.Pais','U') iS NULL
	CREATE TABLE Pais(
		ID_PAIS INT IDENTITY(1,1) CONSTRAINT PK_Pais PRIMARY KEY,
		NOMBRE VARCHAR(50) NOT NULL,
		PBI BIGINT
	);
