USE db_mundial;
go

IF OBJECT_ID('dbo.Mundial','U') is NULL
	CREATE TABLE Mundial(
		ID_MUNDIAL INT IDENTITY(1,1) CONSTRAINT PK_Mundial PRIMARY KEY,
		ID_PAIS INT NOT NULL CONSTRAINT FK_Mundial_Pais REFERENCES Pais(ID_PAIS),
		ACTIVIDAD_FECHA_INICIO DATE,
		ACTIVIDAD_FECHA_FIN DATE,
		TAMANIO_SELECCION_MINIMO INT NOT NULL,
		TAMANIO_SELECCION_MAXIMO INT NOT NULL,
		CAMBIOS_VENTANAS INT NOT NULL,
		CAMBIOS_CANTIDAD INT NOT NULL,
		SUSPENSION_TARJETAS_MAXIMAS INT NOT NULL,
		SUSPENSION_TIEMPO INT NOT NULL
	);
