USE db_mundial;
go

IF OBJECT_ID('dbo.Seleccion','U') is NULL 
	create table Seleccion(
		ID_SELECCION INT IDENTITY(1,1) CONSTRAINT PK_Seleccion PRIMARY KEY,
		ID_PAIS INT NOT NULL CONSTRAINT FK_Pais_Seleccion REFERENCES Pais(ID_PAIS),
		ID_MUNDIAL INT NOT NULL CONSTRAINT FK_Seleccion_Mundial REFERENCES Mundial(ID_MUNDIAL),
		ID_GRUPO INT NOT NULL CONSTRAINT FK_Seleccion_Grupo REFERENCES Grupo(ID_GRUPO),
		CONFEDERACION VARCHAR(45) NOT NULL
	);
